doctrine:
    dbal:
        default_connection: default
        connections:
            default:
                url: '%env(resolve:DATABASE_URL)%'
                charset: utf8mb4
                driver: pdo_mysql
                options:
                    1002: "SET NAMES 'utf8mb4' COLLATE 'utf8mb4_unicode_ci'"
                default_table_options:
                    charset: utf8mb4
                    collate: utf8mb4_unicode_ci
                server_version: '8.0'
        types:
            uuid_binary: App\Infrastructure\Utilities\FieldTypes\UuidBinary

    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true
        mappings:
            User:
                is_bundle: false
                type: xml
                dir: '%kernel.project_dir%/src/Infrastructure/Doctrine/Repository/User'
                prefix: 'App\Domain\Model\User'
                alias: User
            WorkEntry:
                is_bundle: false
                type: xml
                dir: '%kernel.project_dir%/src/Infrastructure/Doctrine/Repository/WorkEntry'
                prefix: 'App\Domain\Model\WorkEntry'
                alias: WorkEntry
            Event:
                is_bundle: false
                type: xml
                dir: '%kernel.project_dir%/src/Infrastructure/Doctrine/Repository/Event'
                prefix: 'App\Domain\Model\Event'
                alias: Event
when@prod:
    doctrine:
        orm:
            auto_generate_proxy_classes: false
            query_cache_driver:
                type: pool
                pool: doctrine.system_cache_pool
            result_cache_driver:
                type: pool
                pool: doctrine.result_cache_pool

    framework:
        cache:
            pools:
                doctrine.result_cache_pool:
                    adapter: cache.app
                doctrine.system_cache_pool:
                    adapter: cache.system
