version: '3.3'

services:
  php:
    container_name: sesame_api_php
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/var/www
      - /var/www/var/cache
      - /var/www/var/log
    environment:
      DATABASE_URL: "mysql://app:p@ssw0rd@mysql:3306/app?serverVersion=8.0&charset=utf8mb4"
    depends_on:
      - mysql
    command: "/bin/bash -c '/var/www/init.sh && php -S 0.0.0.0:9000 -t public'"
    ports:
      - "9000:9000"

  mysql:
    container_name: sesame_api_mysql
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: app
      MYSQL_USER: app
      MYSQL_PASSWORD: p@ssw0rd
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"
    restart: always

volumes:
  mysql_data:
