# Create user
POST http://localhost:9000/users/add
Content-Type: application/json

{
  "name": "testName",
  "email": "testlluis2@gmail.com",
  "password": "defaultPassword"
}

###

# Update user
# /users/{userId}
# Note: Replace {userId} with the id of the user you want to update.
PUT http://localhost:9000/users/c813eb88-a6b8-11ef-acd8-0242ac120003
Content-Type: application/json

{
  "name": "updatedName",
  "email": "testLluisUpdated@gmail.com",
  "password": "testLluisUpdatedPassword"
}

###

# [SOFT] Delete user
# /users/{userId}
# Note: Replace {userId} with the id of the user you want to delete.
# This is a soft delete. The user will not be permanently removed from the database, but their deleted date will be updated.
DELETE http://localhost:9000/users/c813eb88-a6b8-11ef-acd8-0242ac120003
Content-Type: application/json

###

# Get a user by id
# /users/{userId}
# Note: Replace {userId} with the id of the user you want to get.
GET http://localhost:9000/users/c813eb88-a6b8-11ef-acd8-0242ac120003
Content-Type: application/json

###

# Create a work entry
# /work-entries/add
# Note: Replace {userId} with the id of the user you want to associate with the work entry.
# The user_id should be the UUID of the user, not their id.
POST http://localhost:9000/work-entries/add
Content-Type: application/json

{
"user_id": "391af0c6-a6c6-11ef-902b-0242ac120003"
}

###

# Update work entry
# /work-entries/{workEntryUuid}/{userUuid}
# Note: Replace {workEntryUuid} with the UUID of the work entry you want to update, and {userUuid} with the UUID of the user associated with the work entry.
PUT http://localhost:9000/work-entries/02667fb2-a6b9-11ef-894f-0242ac120003/c813eb88-a6b8-11ef-acd8-0242ac120003
Content-Type: application/json

{
  "start_date": "2024-11-19T15:00:00",
  "end_date": "2024-11-19T16:00:00"
}


###

# [SAFE] Delete work entry
# /work-entries/{workEntryUuid}/{userUuid}
# Note: Replace {workEntryUuid} with the UUID of the work entry you want to delete, and {userUuid} with the UUID of the user associated with the work entry.
DELETE http://localhost:9000/work-entries/02667fb2-a6b9-11ef-894f-0242ac120003/c813eb88-a6b8-11ef-acd8-0242ac120003
Content-Type: application/json

###

# Get work entry
# /work-entries/{workEntryUuid}/{userUuid}
# Note: Replace {workEntryUuid} with the UUID of the work entry you want to get, and {userUuid} with the UUID of the user associated with the work entry.
GET http://localhost:9000/work-entries/02667fb2-a6b9-11ef-894f-0242ac120003/c813eb88-a6b8-11ef-acd8-0242ac120003
Content-Type: application/json

###

# Login return token as is correctly authenticated
# Check user name and password of updated user, and replace values
POST http://localhost:9000/login_check
Content-Type: application/json

{
  "username": "testLluisUpdated@gmail.com",
  "password": "testLluisUpdatedPassword"
}

###

# Start work entry
# Change what is after Bearer for the id returned in http request executed before this one
# Bearer {token}
POST http://localhost:9000/api/work-entries/start_work_entry
Content-Type: application/json,
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJpYXQiOjE3MzIwNTAwMjMsImV4cCI6MTczMjA1MzYyMywicm9sZXMiOlsiUk9MRV9VU0VSIl0sInVzZXJuYW1lIjoidGVzdExsdWlzVXBkYXRlZEBnbWFpbC5jb20ifQ.ux28qWxNZAECzGyAlMCIECHA_VJKS6Cfc_WiB9eRXvlgeUG2LjBeuiwAjodRMXycFyONK7aypI3y7qvCgvNSL4SkH-_BUed3f-XjFM6JasJ0ZYhxHlzRRCAd_aiijtfCLUSB98EEFaZzIm2rXk0qOeS0i8mtdxi8-zoVy26-k-Wj0ff6TE404gOhGiftsDeBBmKTMEXm3XhpJo7ONjvLY75lXzH4o4SqK4ugWb9ugt3ISiWpYNnarxAmm2UpeB6JWnGOVmBKzb1tr_MRLVaouWueUzrG74Dw1lYDC7qwF_I1g08s-9KAxQcCTeyOQaiRhfIZGR5Djowuv4AnKgfVRA

{
}

###


# End work entry
# /api/work-entries/end_work_entry/{workEntryUuid}
# Change what is after Bearer for the token used in http request executed before
POST http://localhost:9000/api/work-entries/end_work_entry/9bc1dc6a-a6b9-11ef-ad1d-0242ac120003
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJpYXQiOjE3MzIwNTAwMjMsImV4cCI6MTczMjA1MzYyMywicm9sZXMiOlsiUk9MRV9VU0VSIl0sInVzZXJuYW1lIjoidGVzdExsdWlzVXBkYXRlZEBnbWFpbC5jb20ifQ.ux28qWxNZAECzGyAlMCIECHA_VJKS6Cfc_WiB9eRXvlgeUG2LjBeuiwAjodRMXycFyONK7aypI3y7qvCgvNSL4SkH-_BUed3f-XjFM6JasJ0ZYhxHlzRRCAd_aiijtfCLUSB98EEFaZzIm2rXk0qOeS0i8mtdxi8-zoVy26-k-Wj0ff6TE404gOhGiftsDeBBmKTMEXm3XhpJo7ONjvLY75lXzH4o4SqK4ugWb9ugt3ISiWpYNnarxAmm2UpeB6JWnGOVmBKzb1tr_MRLVaouWueUzrG74Dw1lYDC7qwF_I1g08s-9KAxQcCTeyOQaiRhfIZGR5Djowuv4AnKgfVRA

{

}

###

# Get all work entries ordered
# Change what is after Bearer for the token used in http request executed before
GET http://localhost:9000/api/work-entries/get_all_from_user
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJpYXQiOjE3MzIwNTAwMjMsImV4cCI6MTczMjA1MzYyMywicm9sZXMiOlsiUk9MRV9VU0VSIl0sInVzZXJuYW1lIjoidGVzdExsdWlzVXBkYXRlZEBnbWFpbC5jb20ifQ.ux28qWxNZAECzGyAlMCIECHA_VJKS6Cfc_WiB9eRXvlgeUG2LjBeuiwAjodRMXycFyONK7aypI3y7qvCgvNSL4SkH-_BUed3f-XjFM6JasJ0ZYhxHlzRRCAd_aiijtfCLUSB98EEFaZzIm2rXk0qOeS0i8mtdxi8-zoVy26-k-Wj0ff6TE404gOhGiftsDeBBmKTMEXm3XhpJo7ONjvLY75lXzH4o4SqK4ugWb9ugt3ISiWpYNnarxAmm2UpeB6JWnGOVmBKzb1tr_MRLVaouWueUzrG74Dw1lYDC7qwF_I1g08s-9KAxQcCTeyOQaiRhfIZGR5Djowuv4AnKgfVRA
