# Create user
POST http://localhost:9000/users/add
Content-Type: application/json

{
  "name": "testName",
  "email": "testlluis2@gmail.com",
  "password": "defaultPassword"
}

###

# Update user
# /users/{userId}
# Note: Replace {userId} with the id of the user you want to update.
PUT http://localhost:9000/users/f996ec30-a719-11ef-ada5-0242ac130003
Content-Type: application/json

{
  "name": "updatedName",
  "email": "testLluisUpdated@gmail.com",
  "password": "testLluisUpdatedPassword"
}

###

# [SOFT] Delete user
# /users/{userId}
# Note: Replace {userId} with the id of the user you want to delete.
# This is a soft delete. The user will not be permanently removed from the database, but their deleted date will be updated.
DELETE http://localhost:9000/users/f996ec30-a719-11ef-ada5-0242ac130003
Content-Type: application/json

###

# Get a user by id
# /users/{userId}
# Note: Replace {userId} with the id of the user you want to get.
GET http://localhost:9000/users/f996ec30-a719-11ef-ada5-0242ac130003
Content-Type: application/json

###

# Create a work entry
# /work-entries/add
# Note: Replace {userId} with the id of the user you want to associate with the work entry.
# The user_id should be the UUID of the user, not their id.
POST http://localhost:9000/work-entries/add
Content-Type: application/json

{
"user_id": "f996ec30-a719-11ef-ada5-0242ac130003"
}

###

# Update work entry
# /work-entries/{workEntryUuid}/{userUuid}
# Note: Replace {workEntryUuid} with the UUID of the work entry you want to update, and {userUuid} with the UUID of the user associated with the work entry.
PUT http://localhost:9000/work-entries/1631680c-a71a-11ef-9872-0242ac130003/f996ec30-a719-11ef-ada5-0242ac130003
Content-Type: application/json

{
  "start_date": "2024-11-19T15:00:00",
  "end_date": "2024-11-19T16:00:00"
}


###

# [SAFE] Delete work entry
# /work-entries/{workEntryUuid}/{userUuid}
# Note: Replace {workEntryUuid} with the UUID of the work entry you want to delete, and {userUuid} with the UUID of the user associated with the work entry.
DELETE http://localhost:9000/work-entries/1631680c-a71a-11ef-9872-0242ac130003/f996ec30-a719-11ef-ada5-0242ac130003
Content-Type: application/json

###

# Get work entry
# /work-entries/{workEntryUuid}/{userUuid}
# Note: Replace {workEntryUuid} with the UUID of the work entry you want to get, and {userUuid} with the UUID of the user associated with the work entry.
GET http://localhost:9000/work-entries/1631680c-a71a-11ef-9872-0242ac130003/f996ec30-a719-11ef-ada5-0242ac130003
Content-Type: application/json

###

# Login return token as is correctly authenticated
# Check user name and password of updated user, and replace values
POST http://localhost:9000/login_check
Content-Type: application/json

{
  "username": "testLluisUpdated@gmail.com",
  "password": "testLluisUpdatedPassword"
}

###

# Start work entry
# Change what is after Bearer for the id returned in http request executed before this one
# Bearer {token}
POST http://localhost:9000/api/work-entries/start_work_entry
Content-Type: application/json,
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJpYXQiOjE3MzIwOTE2NjMsImV4cCI6MTczMjA5NTI2Mywicm9sZXMiOlsiUk9MRV9VU0VSIl0sInVzZXJuYW1lIjoidGVzdExsdWlzVXBkYXRlZEBnbWFpbC5jb20ifQ.MqdIhqnzceEAq4I0-46eZirKk0JELm5EiZodpjyNSiwHqlYYLphR4u0cQ6ubRYKqJbDt6bso0hnjeHqisKxHy1YiH03FqN1pjz2f1h3u1CxyzcYVaxKP4Tx0Tr5aFbicJWorAYftR01DE6WOe_jcO_fWfem5TH6LkwQWmz8ZEF6kLaapVBq3Ec1PiuajlvXoVH4UJTL-yUUAK0yQt-mvY9ZzqOllFzEI52-7AH3UleiSU-u3OSrLChR_3b1-4zWiRFt92ivhIQ-idyrsrAiBikn2qm9SR01cuUIK8p1slLVKBBEHtAAokgGUUt5DkO-4giobYQ8w_il1GZtdAqwZTw

{
}

###


# End work entry
# /api/work-entries/end_work_entry/{workEntryUuid}
# Change what is after Bearer for the token used in http request executed before
POST http://localhost:9000/api/work-entries/end_work_entry/1631680c-a71a-11ef-9872-0242ac130003
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJpYXQiOjE3MzIwOTE2NjMsImV4cCI6MTczMjA5NTI2Mywicm9sZXMiOlsiUk9MRV9VU0VSIl0sInVzZXJuYW1lIjoidGVzdExsdWlzVXBkYXRlZEBnbWFpbC5jb20ifQ.MqdIhqnzceEAq4I0-46eZirKk0JELm5EiZodpjyNSiwHqlYYLphR4u0cQ6ubRYKqJbDt6bso0hnjeHqisKxHy1YiH03FqN1pjz2f1h3u1CxyzcYVaxKP4Tx0Tr5aFbicJWorAYftR01DE6WOe_jcO_fWfem5TH6LkwQWmz8ZEF6kLaapVBq3Ec1PiuajlvXoVH4UJTL-yUUAK0yQt-mvY9ZzqOllFzEI52-7AH3UleiSU-u3OSrLChR_3b1-4zWiRFt92ivhIQ-idyrsrAiBikn2qm9SR01cuUIK8p1slLVKBBEHtAAokgGUUt5DkO-4giobYQ8w_il1GZtdAqwZTw

{

}

###

# Get all work entries ordered
# Change what is after Bearer for the token used in http request executed before
GET http://localhost:9000/api/work-entries/get_all_from_user
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJpYXQiOjE3MzIwOTA3MjYsImV4cCI6MTczMjA5NDMyNiwicm9sZXMiOlsiUk9MRV9VU0VSIl0sInVzZXJuYW1lIjoidGVzdExsdWlzVXBkYXRlZEBnbWFpbC5jb20ifQ.2NnpbQeNvsieGL4Rq1p41YHkfR4XIYEM4oXAlrz0Ll5ta31uwwrgbv4FTQPaZzFjCz862P2JXjWIRuq_9RJuhMwDWq8Xm5MyaQFh4umoH8koZU3eMtLKlZtlK4lpFcfCqVoxelFJ8ll-bbmoTpwjtr2VsjCEtby5-lilCjDbyrc3ym9rCXxgjje_zE2LBAhlF0OqFBwbudnXOdpZ8m8dORygAR-aHarGRKpeQPHZMKQl6voTIpxNrXeH-Y9_V8W8ywVZHTb4gsky1zIZb7aeEIb9Qo0fNpsTS043iqS1Ib55CnLO-FkqR0Osu3JvptLR-Vqpj9xLBqMOdDDlyKfthg
